### ISSUE TITLE
Sample Error

### ISSUE THREAD

**Issue by kevinsui581** [jcangas/puremvc-delphi-standard-framework#2]
when ran the sample, raise exception
Error reading UserGrid.ColWidth:Invalid property value
![image](https://cloud.githubusercontent.com/assets/11595772/14629255/ef246dae-0637-11e6-9bcb-c8293be0b670.png)

**Comment by jcangas** [comment]
Thanks for reporting it. Some modern Delphi versions add some properties to dfm. Please, try this: open this form in your side and ignore complaints about invalid properties. Then save the form, build and run the sample. Let me know if this clear the issue.

**Comment by kevinsui581** [comment]
the issue still exists, after open and save; i use xe10.

**Comment by jcangas** [comment]
Hi. I tested again with D10 Seattle and it works. I cannot reproduce this issue. Anyway I fixed some bugs in the sample. I pushed the changes to branch develop. Note the hew folder D230-D10 for Seattle vs. Please check if this changes works for you also.
